apiVersion: v1
kind: Service
metadata:
  name: app1
  labels:
    app: app1
spec:
  ports:
  - name: http-app1
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: app1