apiVersion: v1
kind: Service
metadata:
  name: app2
  labels:
    app: app2
spec:
  ports:
  - name: http-app2
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: app2