apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  nginx.conf: |
    user nginx;
    worker_processes  1;
    events {
      worker_connections  10240;
    }
    http {
      server {
          listen       80;
          location / {
            root   /usr/share/nginx/html; #Change this line
            index  index.html index.htm;
        }
          location /app1 {
            proxy_pass http://app1.default.svc.cluster.local:8080/;
        }
          location /app2 {
            proxy_pass http://app2.default.svc.cluster.local:8080/;
        }
      }
    }